CREATE TABLE IF NOT EXISTS commits(
    id integer PRIMARY KEY,
    repo_id INTEGER NOT NULL,
    commit_sha VARCHAR(255) NOT NULL,
    commit_message TEXT NOT NULL,
    commit_author_name VARCHAR(255) NOT NULL,
    commit_author_email VARCHAR(255) NOT NULL,
    commit_author_date INTEGER NOT NULL,
    commit_committer_name VARCHAR(255) NOT NULL,
    commit_committer_email VARCHAR(255) NOT NULL,
    commit_committer_date INTEGER NOT NULL,
    author_login VARCHAR(255) NOT NULL,
    author_id INTEGER NOT NULL,
    author_avatar_url VARCHAR(255) NOT NULL,
    author_type VARCHAR(255) NOT NULL,
    committer_login VARCHAR(255) NOT NULL,
    committer_id INTEGER NOT NULL,
    committer_avatar_url VARCHAR(255) NOT NULL,
    committer_type VARCHAR(255) NOT NULL,
    stats_addtions INTEGER NOT NULL,
    stats_deletions INTEGER NOT NULL,
    stats_total INTEGER NOT NULL,
    FOREIGN KEY (repo_id) REFERENCES repo (id)
);